services:
  # Next.js Client
  nextjs-app:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - '3000:3000'
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - JWT_SECRET=${JWT_SECRET}
      - API_URL=${API_URL}
    volumes:
      - ./client:/app
    env_file:
      - .env
    networks:
      - app-network
    command: ['npm', 'run', 'build']
    entrypoint: ['npm', 'start']

  # Node.js API Server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - '4000:4000'
    environment:
      - API_SECRET=${API_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - NODE_ENV=${NODE_ENV}
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network
    env_file:
      - .env
    command: ['npm', 'run', 'start']

networks:
  app-network:
    driver: bridge
