import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import { LoginStatus, Nav, NavLink } from '@/components/nav';
import AuthProvider from './providers/AuthProvider';
import { getServerSession } from 'next-auth';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang='en'>
      <body className={inter.className}>
        <AuthProvider session={session}>
          <Nav className='z-20'>
            <NavLink href='/'>Home</NavLink>
            <NavLink href='/flights'>Search Flights</NavLink>
            <NavLink href='/profile'>Profile</NavLink>
            <NavLink href='/admin-dashboard'>Admin Access</NavLink>
            <LoginStatus />
          </Nav>
          {children}
          <Toaster />
        </AuthProvider>
      </body>
    </html>
  );
}
